openapi: 3.0.0

info:
  description: Service responsible for managing the rooms for the calls.
  version: 1.0.0
  title: call-service
servers:
  - url: /
paths:
  /healthy:
    get:
      tags:
        - Sanity check
      responses:
        200:
          description: Ok.
        500:
          description: Server internal error.
  /calls/v1/rooms:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewRoom"
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewRoomResponse"
        500:
          description: Server internal error.
  /calls/v1/rooms/{roomName}:
    delete:
      parameters:
        - name: roomName
          in: path
          description: identificador do evento
          required: true
          schema:
            type: string
      responses:
        200:
          description: Ok.
        500:
          description: Server internal error.
components:
  schemas:
    NewRoom:
      type: object
      required:
        - roomName
      properties:
        roomName:
          type: string
          description: Name of the room at Daily
    NewRoomResponse:
      type: object
      required:
        - name
        - url
        - id
      properties:
        id:
          type: string
          description: Identifier of the room from Daily
        name:
          type: string
          description: Name of the room at Daily
        url:
          type: string
          description: URL to join the conference



