openapi: 3.0.0

info:
  description: Service responsible for managing the rooms for the calls.
  version: 1.0.0
  title: call-service
servers:
  - url: /
paths:
  /healthy:
    get:
      summary: Health check to see if the service is running
      tags:
        - Sanity check
      responses:
        200:
          description: Ok.
        500:
          description: Server internal error.
  /calls/v1/rooms:
    get:
      summary: Retrieve all the meeting that have been created since the last time the service has restarted
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomResponseList"
        500:
          description: Server internal error.
    post:
      summary: Will create a new meeting at daily and persist the information in memory
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewRoom"
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomResponse"
        500:
          description: Server internal error.
  /calls/v1/rooms/{roomId}:
    get:
      summary: Retrieve the informations about a specific meeting, including the statistics
      parameters:
        - name: roomId
          in: path
          description: It will be used as the room name at daily
          required: true
          schema:
            type: string
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomInfo"
        500:
          description: Server internal error.
    delete:
      summary: Delete the room from daily. Not remove the data that is persisted in memory with the statistics of the meeting.
      parameters:
        - name: roomId
          in: path
          description: It will be used as the room name at daily
          required: true
          schema:
            type: string
      responses:
        200:
          description: Ok.
        500:
          description: Server internal error.
  /calls/v1/rooms/{roomId}/stats:
    post:
      summary: Add a statistic from a specific user to the meeting
      parameters:
        - name: roomId
          in: path
          description: Room identifier, the same from daily
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewStats"
      responses:
        200:
          description: Ok.
        500:
          description: Server internal error.
components:
  schemas:
    NewRoom:
      type: object
      required:
        - roomId
      properties:
        roomId:
          type: string
          description: Identifier of the room. It will be used as the room name at daily
    RoomResponse:
      type: object
      required:
        - roomId
        - url
      properties:
        roomId:
          type: string
          description: Identifier of the room. It will be the name from daily.
        url:
          type: string
          description: URL to join the conference
    RoomInfo:
      type: object
      required:
        - roomId
        - url
        - users
      properties:
        roomId:
          type: string
          description: Identifier of the room. It will be the name from daily.
        url:
          type: string
          description: URL to join the conference
        users:
          type: object
          description: Users that have joined the conference
          properties:
            id:
              type: string
              description: User identifier
            name:
              type: string
              description: Name of the user
            videoStatistics:
              type: object
              description: statistics collected from the user during the meeting
              required:
                - videoRecvBitsPerSecond
                - videoRecvPacketLoss
                - videoSendBitsPerSecond
                - videoSendPacketLoss
              properties:
                videoRecvBitsPerSecond:
                  type: array
                  items:
                    type: number
                  description: Number of bits received per second, retrieved from daily
                videoRecvPacketLoss:
                  type: array
                  items:
                    type: number
                  description: The worst received packet loss number seen for a two-second period, retrieved from daily
                videoSendBitsPerSecond:
                  type: array
                  items:
                    type: number
                  description: Number of bits send per second, retrieved from daily
                videoSendPacketLoss:
                  type: array
                  items:
                    type: number
                  description: the worst send packet loss number seen for a two-second period, retrieved from daily

    RoomResponseList:
      type: array
      items:
        $ref: '#/components/schemas/RoomResponse'
    NewStats:
      type: object
      required:
        - userInfo
        - stats
      properties:
        userInfo:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: string
              description: User identifier retrieved from daily
            name:
              type: string
              description: Name of the user retrieved from daily
        stats:
          type: object
          required:
            - videoRecvBitsPerSecond
            - videoRecvPacketLoss
            - videoSendBitsPerSecond
            - videoSendPacketLoss
          properties:
            videoRecvBitsPerSecond:
              type: number
              description: Number of bits received per second, retrieved from daily
            videoRecvPacketLoss:
              type: number
              description: The worst received packet loss number seen for a two-second period, retrieved from daily
            videoSendBitsPerSecond:
              type: number
              description: Number of bits send per second, retrieved from daily
            videoSendPacketLoss:
              type: number
              description: the worst send packet loss number seen for a two-second period, retrieved from daily
